blog/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import url
from django.contrib import admin
from blog import views
from django.views.static import serve
from blog_s19 import settings
import re

from blog import views

urlpatterns = [
    # # 个人站点页面
    # url(r'^(?P<username>\w+)/$', views.home_site),
    # # 归档
    # url(r'^(?P<username>\w+)/(?P<condition>cate|tag|date)/(?P<param>.*)', views.home_site),
    # # 文章详细页
    # url(r'^(?P<username>\w+)/articles/(?P<article_id>\d+)', views.article_detail),
    # # 后台管理
    # url(r'^backend/$', views.backend),
    # url(r'^backend/add_article/$', views.add_article),
    # # 点赞
    # url(r'^up_down/$', views.up_down),
    # # 评论
    # url(r'^comment/$', views.comment),

    # 后台管理
    url(r'^backend/$', views.backend),
    url(r'^backend/add_article/$', views.add_article),
    # 点赞
    url(r'^up_down/$', views.up_down),
    # 评论
    url(r'^comment/$', views.comment),
    # 个人站点页面
    url(r'^(?P<username>\w+)/$', views.home_site),

    # 归档
    url(r'^(?P<username>\w+)/(?P<condition>cate|tag|date)/(?P<param>.*)', views.home_site),
    # 文章详细页
    url(r'^(?P<username>\w+)/articles/(?P<article_id>\d+)', views.article_detail),



]

blog_s19/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from blog_s19 import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/',views.login),
    url(r'^get_valid_img/',views.get_valid_img),
    url(r'^index/',views.index),
    url(r'^register/',views.register),
    url(r'^$',views.index),
    url(r'^logout/$',views.log_out),

    #blog分发
    url(r'^blog/',include('blog.urls')),
    #media配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    #文本编辑器上传
    url(r'^upload_img/',views.upload_img),


]

blog/views.py
from django.shortcuts import render,HttpResponse,redirect

# Create your views here.

# import PIL
import re
from django.http import JsonResponse
from django.contrib import auth

def login(request):
    if request.method == "POST":
        user = request.POST.get("user")
        pwd = request.POST.get("pwd")
        input_valid_codes = request.POST.get("valid_code")

        #校验验证码
        keep_valid_codes=request.session.get('keep_valid_codes')
        '''
        1  拿到cookie中sessionid对应的随机字符串
        2  在django-session表中过滤记录
        3  ....
        '''
        login_response={"user":None,"error_msg":""}

        if keep_valid_codes.upper()==input_valid_codes.upper():
            user = auth.authenticate(username=user,password=pwd)
            if user:
                auth.login(request,user)
                login_response['user']=user.username
            else:
                login_response['error_msg']="用户名或密码错误"
        else:
            login_response['error_msg']="验证码错误"

        import json
        return HttpResponse(json.dumps(login_response))
    else:
        return render(request,"login.html")

#获取验证码图片
def get_valid_img(request):
    from blog.utils import valid_code

    data=valid_code.get_valid_value(request)

    return HttpResponse(data)


def index(request):
    print("==",request.user)
    article_list=Article.objects.all()

    return render(request,"index.html",{"article_list":article_list})



from django import forms
from django.forms import widgets
from .models import *
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError

#  按form表单构建forms组件
class RegForm(forms.Form):
    user=forms.CharField(min_length=4,max_length=8,
                widget=widgets.TextInput(attrs={"class":"form-control"}),
                         error_messages={"min_length":"输入过短，最少4个字符","max_length":"输入过长，最多4个字符","required":"必填"}
                         )
    pwd=forms.CharField(min_length=5,
        widget=widgets.PasswordInput(attrs={"class": "form-control"}),
                        error_messages={"min_length":"输入过短，最少5个字符", "required": "必填"}
    )
    repeat_pwd=forms.CharField(min_length=5,
        widget=widgets.PasswordInput(attrs={"class": "form-control"}),
                               error_messages={"min_length":"输入过短，最少5个字符", "required": "必填"}
    )
    email=forms.EmailField(min_length=5,
        widget=widgets.EmailInput(attrs={"class": "form-control"}),
        error_messages={"min_length":"输入过短，最少5个字符", "required": "必填"}
    )

#钩子函数
    def clean_user(self):
        val=self.cleaned_data.get("user")

        import re
        # if not UserInfo.objects.filter(username=val):
        #     return val
        # else:
        #     raise ValidationError("")

        if not val.isdigit():
            return val
        else:
            raise ValidationError("用户名不能是纯数字！")

    def clean_pwd(self):
        val=self.cleaned_data.get("pwd")

        if not val.isdigit():
            return val
        else:
            raise ValidationError("密码不能是纯数字！")

#注册
def register(request):
    if request.is_ajax():
        print("request.POST",request.POST) # <QueryDict: {'user': ['123'], 'pwd': ['1231'], 'repeat_pwd': ['1231'], 'email': ['123'], 'csrfmiddlewaretoken': ['PjMKenIgrFYWY52U5EcYbkfmib2EiMzK19K5xv4qBon5XZbPDkuiMhMf2LqaV2wy']}>
        print("request.FILES",request.FILES) # request.FILES <MultiValueDict: {'avatar_img': [<InMemoryUploadedFile: linhaifeng.jpg (image/jpeg)>]}>
        form_obj = RegForm(request.POST)

        reg_response={"user":None,"error_mes":None}

        if form_obj.is_valid():
            user=form_obj.cleaned_data.get("user")
            pwd=form_obj.cleaned_data.get("pwd")
            email=form_obj.cleaned_data.get("email")
            avatar_img=request.FILES.get("avatar_img")
            if avatar_img:
                 print("avatar_img....",avatar_img)
                 user=UserInfo.objects.create_user(username=user,password=pwd,email=email,avatar=avatar_img)
            else:
                user = UserInfo.objects.create_user(username=user, password=pwd, email=email)

            reg_response["user"]=user.username

        else:
            reg_response["error_mes"]=form_obj.errors
        return JsonResponse(reg_response)
    else:
        #实例化form组件的类
        form_obj=RegForm()
        return render(request,"reg.html",{"form_obj":form_obj})

#注销
def log_out(request):
    auth.logout(request)
    return redirect("/login")

#个人站点设计
def home_site(request,username,**kwargs):
    '''
    个人站点设计
    :param request: 请求数据对象
    :return:
    '''
    print("kwargs",kwargs)
    print(username)
    user=UserInfo.objects.filter(username=username).first()
    if not user:
        return HttpResponse("<h3>404</h3>")

    # 当前访问站点对象

    blog=user.blog

    # 当前访问站点的所有文章
    if not kwargs:
        article_list=Article.objects.filter(user=user)
    else:
        condition=kwargs.get("condition")
        param=kwargs.get("param") # 2018-02
        if condition=="cate":
             article_list = Article.objects.filter(user=user).filter(homeCategory__title=param)
        elif condition=="tag":
            article_list = Article.objects.filter(user=user).filter(tags__title=param)
        else:
            year,month=param.split("-")
            article_list = Article.objects.filter(user=user).filter(create_time__year=year,create_time__month=month)


    #查询当前站点所有分类
    # # 方式1：
    # category_list=Category.objects.filter(blog=blog)
    # print(category_list)

    # 方式2：查询当前站点的每一个分类名称以及对应的文章数：分组查询
    # from django.db.models import Count,Max
    # cate_list=Category.objects.filter(blog=blog).annotate(count=Count("article")).values_list("title","count")
    # print(cate_list)
    #
    # # 查询当前站点的每一个标签的名称以及对应的文章数：分组查询
    # tag_list=Tag.objects.filter(blog=blog).annotate(count=Count("article")).values_list("title","count")
    # print(tag_list)
    #
    # # 日期归档
    # date_list=Article.objects.filter(user=user).extra(select={"archive_date": "strftime('%%Y-%%m',create_time)"}).values("archive_date").annotate(c=Count("nid")).values_list("archive_date","c")
    # print(date_list)

    return render(request,"blog/home_site.html",locals())


# def get_data(username):
#     user = UserInfo.objects.filter(username=username).first()
#     blog = user.blog
#     from django.db.models import Count, Max
#     cate_list = Category.objects.filter(blog=blog).annotate(count=Count("article")).values_list("title", "count")
#     print(cate_list)
#     # 查询当前站点的每一个标签的名称以及对应的文章数：分组查询
#     tag_list = Tag.objects.filter(blog=blog).annotate(count=Count("article")).values_list("title", "count")
#     print(tag_list)
#     # 日期归档
#     date_list = Article.objects.filter(user=user).extra(
#         select={"archive_date": "strftime('%%Y-%%m',create_time)"}).values("archive_date").annotate(
#         c=Count("nid")).values_list("archive_date", "c")
#     print(date_list)
#
#     return {"username":username,"blog":blog,"cate_list":cate_list,"tag_list":tag_list,"date_list":date_list}

#文章详情页
# def article_detail(request,username,article_id):
#     ret=get_data(username)
#
#     article_obj=Article.objects.filter(pk=article_id).first()
#     ret["article_obj"]=article_obj
#     return render(request,"blog/artcile_detail.html",ret)

def article_detail(request,username,article_id):

    article_obj=Article.objects.filter(pk=article_id).first()

    comment_list=Comment.objects.filter(article_id=article_id)
    return render(request,"blog/artcile_detail.html",{"article_obj":article_obj,"username":username,"comment_list":comment_list})

import json
from django.db.models import F
from django.http import JsonResponse
from django.db import transaction

def up_down(request):
    print(request.POST)

    article_id=request.POST.get("article_id")
    is_up=json.loads(request.POST.get("is_up"))
    user_id=request.user.pk
    print(is_up)

    res={"state":True,"err":""}
    try:
        # 处理事务
        with transaction.atomic():
            obj=ArticleUpDown.objects.create(user_id=user_id,article_id=article_id,is_up=is_up)
            if is_up:
                 Article.objects.filter(pk=article_id).update(up_count=F('up_count')+1)
            else:
                Article.objects.filter(pk=article_id).update(down_count=F('down_count') + 1)
    except Exception as e:
        obj=ArticleUpDown.objects.filter(user_id=user_id,article_id=article_id).first()
        res["state"]=False
        res["err"]=obj.is_up

    return JsonResponse(res)

def comment(request):
    content=request.POST.get('content')
    article_id=request.POST.get('article_id')
    pid=request.POST.get('pid')
    user_id=request.user.pk
    res={}
    with transaction.atomic():
        if pid: # 保存子评论
            obj = Comment.objects.create(content=content, article_id=article_id, user_id=user_id,parent_comment_id=pid)
        else:
            # 保存根评论
            obj = Comment.objects.create(content=content, article_id=article_id, user_id=user_id)

        Article.objects.filter(pk=article_id).update(comment_count=F("comment_count")+1)
    res["create_time"]=obj.create_time.strftime("%Y-%m-%d %H:%M")
    res["content"]=obj.content
    return JsonResponse(res)


def backend(reqeust):
    username=reqeust.user

    article_list=Article.objects.filter(user=reqeust.user)


    return render(reqeust,"blog/backend.html",locals())

def add_article(reqeust):

    username=reqeust.user.username
    return render(reqeust,"blog/add_article.html",locals())


def upload_img(reqeust):
    print(reqeust.FILES)
    obj=reqeust.FILES.get("put_img")
    name=obj.name

    from blog_s19 import settings
    import os
    path=os.path.join(settings.MEDIA_ROOT,"add_article_img",name)

    f=open(path,"wb")

    for line in obj:
        f.write(line)
    f.close()

    res={
        "url":"/media/add_article_img/"+name,
        "error":0
    }
    import json
    return HttpResponse(json.dumps(res))

templates/include_demo.html
<div>
    <p style="color: darkgrey">hello world</p>
    <p style="background-color: #2aabd2">hi hx</p>
</div>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bs/css/bootstrap.css">
    <script src="/static/js/jquery-3.1.1.js"></script>
    <script src="/static/bs/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/css/index.css">

</head>
<body>


<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand title" href="#">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">园子 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">随笔</a></li>
                <li><a href="#">新闻</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li><a href="/logout/">注销</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改密码</a></li>
                            <li><a href="#">个人主页</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}


            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
               {% include 'include_demo.html' %}
            </div>
        </div>
        <div class="col-md-6">

            <div class="article_list">

                {% for article in article_list %}
                    <div class="article_item">
                        <div class="row"><h5><a href="/blog/{{ article.user.username }}/articles/{{ article.pk }}">{{ article.title }}</a></h5></div>
                        <div class="row">
                            <img class="col-md-2" width="60" height="60" src="{{ article.user.avatar.url }}" alt="">
                            <p class="col-md-10 desc">{{ article.desc }}</p>
                        </div>
                        <div class="row small">
                            <span><a href="">{{ article.user.username }}</a></span>&nbsp;&nbsp;
                            <span>发布于&nbsp;{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-comment">评论(0)</span>&nbsp;&nbsp;
                            <span class="glyphicon glyphicon-thumbs-up">点赞(0)</span>&nbsp;&nbsp;
                        </div>
                        <hr>
                    </div>
                {% endfor %}

            </div>
            <nav class="pull-right" aria-label="Page navigation">
                <ul class="pagination">
                    <li>
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>


        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                {% include 'include_demo.html' %}
            </div>

            <div class="panel panel-danger">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>

</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bs/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/login.css">
    <script src="/static/js/jquery-3.1.1.js"></script>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                 <div class="form-group">
                    <label for="user">用户名</label>
                    <input type="text" class="form-control" id="user" placeholder="Username">
                  </div>
                <div class="form-group">
                    <label for="pwd">密码</label>
                    <input type="password" class="form-control" id="pwd" placeholder="Password">
                </div>
                 <div class="form-group">
                    <label for="valid"> 验证码</label>
                    <div class="row">
                        <div class="col-md-6">
                           <input type="text" class="form-control" id="valid" placeholder="valid">
                        </div>
                        <div class="col-md-6">
                            <img id="valid_img" width="220" height="40" src="/get_valid_img/" alt="">
                        </div>
                    </div>
                </div>
                {% csrf_token %}
                <input type="button" class="btn btn-primary" value="submit" id="login_btn"><span class="error"></span>
            </form>
        </div>
    </div>
</div>

<script>
    // 验证码刷新
    $("#valid_img").click(function () {
        $(this)[0].src+="?"
    });

    // ajax请求验证

    $("#login_btn").click(function () {
        
        $.ajax({
            url:"/login/",
            type:"post",
            data:{
                "user":$("#user").val(),
                "pwd":$("#pwd").val(),
                "valid_code":$("#valid").val(),
                "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val()
            },
            success:function (data) {   // {"user":"","error_meg":""}
                console.log(data);
                var data=JSON.parse(data);
                if(data.user){
                    // 登录成功
                    location.href="/index/"

                }
                else {
                    $(".error").html(data.error_msg).css('color',"red")

                    setTimeout(function () {
                        $(".error").html("")
                    },1000)
                }
            }
        })
        
    })
</script>

</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bs/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/reg.css">
    <script src="/static/js/jquery-3.1.1.js"></script>
</head>
<body>
<h3>注册页面</h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form>
                <div class="form-group">
                    <label for="id_user">用户名</label>
                    {{ form_obj.user }}  <span class="pull-right"></span>

                </div>
                <div class="form-group">
                    <label for="id_pwd">密码</label>
                    {{ form_obj.pwd }} <span class="pull-right"></span>
                </div>
                <div class="form-group">
                    <label for="id_repeat_pwd">确认密码</label>
                    {{ form_obj.repeat_pwd }} <span class="pull-right"></span>
                </div>
                <div class="form-group">
                    <label for="id_email">邮箱</label>
                    {{ form_obj.email }} <span class="pull-right"></span>
                </div>

                <div class="form-group">

                        <label for="avatar">头像&nbsp;&nbsp;&nbsp;<img id="avatar_img" width="60" height="60" src="http://127.0.0.1:8000/static/img/default.png" alt=""></label>
                        <input type="file" id="avatar">
                </div>
                {% csrf_token %}
                <input type="button" class="btn btn-primary" value="submit" id="reg_btn">
            </form>
        </div>
    </div>
</div>

<script>

    // ajax请求验证

    $("#reg_btn").click(function () {

        // 基于ajax 进行文件上传时，需要利用form_data=new FormData();
        var form_data=new FormData();
        form_data.append("user",$("#id_user").val());
        form_data.append("pwd",$("#id_pwd").val());
        form_data.append("repeat_pwd",$("#id_repeat_pwd").val());
        form_data.append("email",$("#id_email").val());
        form_data.append("csrfmiddlewaretoken",$("[name='csrfmiddlewaretoken']").val());
        form_data.append("avatar_img",$("#avatar")[0].files[0]);


        $.ajax({
            url: "/register/",
            type: "post",
            processData:false,
            contentType:false,
            data: form_data,
            success: function (data) {   // {"user":"","error_meg":""}


                if (data.user){   //   注册成功
                    location.href="/login/"
                }
                else {            // 注册失败

                 var errors_dict=data.error_mes;
                 //     清空操作
                 $("form span").html("");
                 $(".form-group").removeClass("has-error");

                 $.each(errors_dict,function (field,error_info) {
                     console.log(field,error_info[0]);

                     $("#id_"+field).next().html(error_info[0]).css("color","red");
                     $("#id_"+field).parent().addClass("has-error");

                 })



                }



            }
        })

    });

    // 头像预览
    $("#avatar").change(function () {
        // 获取用户选中的文件
        var choose_file=$("#avatar")[0].files[0];
        // JS 的文件阅读器
        var reader=new FileReader();
        reader.readAsDataURL(choose_file);

        reader.onload=function(){
            $("#avatar_img").attr("src",this.result)
        };
    })


</script>

</body>
</html>